title: CS Lab Notebook - Lilian Wu
description: "August 2023 to June 2024"
owner_name: Lilian Wu
github_username: LiliWuu
github_repo: "lilian"
baseurl: "/lilian"
future: true
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/LiliWuu"}
    - { platform: x, user_url: "https://twitter.com/dumdumsheep3" }
    - { platform: youtube, user_url: "https://www.youtube.com/channel/UChzE0MFYE4HOCpVURI6vBTA" }      
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
header_pages:
  - navigation/compsci.md
  - navigation/search.html
  - navigation/about.md
  - navigation/tags.md